//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     DSS Runtime Version: 2.0.730.3
//     CLR Runtime Version: 2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using System;
using System.Collections.Generic;
using W3C.Soap;
using dssopencv = Robotics.DssOpenCV;


namespace Robotics.DssOpenCV
{
    
    
    /// <summary>
    /// DssOpenCV Contract class
    /// </summary>
    public sealed class Contract
    {
        
        /// <summary>
        /// The Dss Service contract
        /// </summary>
        [DataMember()]
        public const String Identifier = "http://schemas.tempuri.org/2008/05/dssopencv.html";
    }
    
    /// <summary>
    /// The DssOpenCV State
    /// </summary>
    [DataContract()]
    public class DssOpenCVState
    {
    }
    
    /// <summary>
    /// DssOpenCV Main Operations Port
    /// </summary>
    [ServicePort()]
    public class DssOpenCVOperations : PortSet<DsspDefaultLookup, DsspDefaultDrop, Get>
    {
    }
    
    /// <summary>
    /// DssOpenCV Get Operation
    /// </summary>
    public class Get : Get<GetRequestType, PortSet<DssOpenCVState, Fault>>
    {
        
        /// <summary>
        /// DssOpenCV Get Operation
        /// </summary>
        public Get()
        {
        }
        
        /// <summary>
        /// DssOpenCV Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) : 
                base(body)
        {
        }
        
        /// <summary>
        /// DssOpenCV Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, Microsoft.Ccr.Core.PortSet<DssOpenCVState,W3C.Soap.Fault> responsePort) : 
                base(body, responsePort)
        {
        }
    }
}
