//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:2.0.50727.3031
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using System;
using System.Collections.Generic;
using W3C.Soap;
using dssopencv2 = Robotics.Dssopencv2;


namespace Robotics.Dssopencv2
{
    
    
    /// <summary>
    /// Dssopencv2 Contract class
    /// </summary>
    public sealed class Contract
    {
        
        /// <summary>
        /// The Dss Service contract
        /// </summary>
        [DataMember()]
        public const String Identifier = "http://schemas.tempuri.org/2008/06/dssopencv2.html";
    }
    
    /// <summary>
    /// The Dssopencv2 State
    /// </summary>
    [DataContract()]
    public class Dssopencv2State
    {
    }
    
    /// <summary>
    /// Dssopencv2 Main Operations Port
    /// </summary>
    [ServicePort()]
    public class Dssopencv2Operations : PortSet<DsspDefaultLookup, DsspDefaultDrop, Get>
    {
    }
    
    /// <summary>
    /// Dssopencv2 Get Operation
    /// </summary>
    public class Get : Get<GetRequestType, PortSet<Dssopencv2State, Fault>>
    {
        
        /// <summary>
        /// Dssopencv2 Get Operation
        /// </summary>
        public Get()
        {
        }
        
        /// <summary>
        /// Dssopencv2 Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) : 
                base(body)
        {
        }
        
        /// <summary>
        /// Dssopencv2 Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, Microsoft.Ccr.Core.PortSet<Dssopencv2State,W3C.Soap.Fault> responsePort) : 
                base(body, responsePort)
        {
        }
    }
}
