//------------------------------------------------------------------------------
// <auto-generated>
//     ??ì½”ë“œ???„êµ¬ë¥??¬ìš©?˜ì—¬ ?ì„±?˜ì—ˆ?µë‹ˆ??
//     ?°í???ë²„ì „:2.0.50727.3031
//
//     ?Œì¼ ?´ìš©??ë³€ê²½í•˜ë©??˜ëª»???™ì‘??ë°œìƒ?????ˆìœ¼ë©? ì½”ë“œë¥??¤ì‹œ ?ì„±?˜ë©´
//     ?´ëŸ¬??ë³€ê²??´ìš©???ì‹¤?©ë‹ˆ??
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using System;
using System.Collections.Generic;
using W3C.Soap;
using dssopencv2 = Robotics.Dssopencv2;


namespace Robotics.Dssopencv2
{
    
    
    /// <summary>
    /// Dssopencv2 Contract class
    /// </summary>
    public sealed class Contract
    {
        
        /// <summary>
        /// The Dss Service contract
        /// </summary>
        [DataMember()]
        public const String Identifier = "http://schemas.tempuri.org/2008/06/dssopencv2.html";
    }
    
    /// <summary>
    /// The Dssopencv2 State
    /// </summary>
    [DataContract]
    public class Dssopencv2State
    {
        public Dssopencv2State()
        {
            
        }


        public Dssopencv2State(int index)
        {
            _Index = index;
        }
        [DataMember, DataMemberConstructor]
        public int _Index;
    }

    

    [DataContract]
    public class ButtonPressRequest
    {
        public ButtonPressRequest()
        {
            
        }


        public ButtonPressRequest(int index)
        {
            _Index = index;
        }
        [DataMember]
        public int _Index;
    }

    

    /// <summary>
    /// Dssopencv2 Main Operations Port
    /// </summary>
    [ServicePort]
    public class Dssopencv2Operations : PortSet<DsspDefaultLookup, DsspDefaultDrop, Subscribe, ButtonPress>
    {
    }
    //, Subscribe, IndexUpdate

    public class Subscribe : Subscribe<SubscribeRequestType, PortSet<SubscribeResponseType, Fault>>
    {
    }


    
    
    public class ButtonPress : Update<ButtonPressRequest, PortSet<DefaultUpdateResponseType, Fault>>
    {
        public ButtonPress()
        {
        }

        public ButtonPress(ButtonPressRequest body)
            : base(body)
        {
        }
    }

    //public class IndexUpdate : Update<Dssopencv2State, PortSet<DefaultUpdateResponseType, Fault>>
    //{
    //    public IndexUpdate()
    //    {

    //    }
    //    public IndexUpdate(Dssopencv2State body)
    //        : base(body)
    //    {
    //    }
    //}

    ///// <summary>
    ///// Dssopencv2 Get Operation
    ///// </summary>
    //public class Get : Get<GetRequestType, PortSet<Dssopencv2State, Fault>>
    //{
        
    //    /// <summary>
    //    /// Dssopencv2 Get Operation
    //    /// </summary>
    //    public Get()
    //    {
    //    }
        
    //    /// <summary>
    //    /// Dssopencv2 Get Operation
    //    /// </summary>
    //    public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) : 
    //            base(body)
    //    {
    //    }
        
    //    /// <summary>
    //    /// Dssopencv2 Get Operation
    //    /// </summary>
    //    public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, Microsoft.Ccr.Core.PortSet<Dssopencv2State,W3C.Soap.Fault> responsePort) : 
    //            base(body, responsePort)
    //    {
    //    }
    //}
}
