//------------------------------------------------------------------------------
// <auto-generated>
//     ??ì½”ë“œ???„êµ¬ë¥??¬ìš©?˜ì—¬ ?ì„±?˜ì—ˆ?µë‹ˆ??
//     ?°í???ë²„ì „:2.0.50727.3031
//
//     ?Œì¼ ?´ìš©??ë³€ê²½í•˜ë©??˜ëª»???™ì‘??ë°œìƒ?????ˆìœ¼ë©? ì½”ë“œë¥??¤ì‹œ ?ì„±?˜ë©´
//     ?´ëŸ¬??ë³€ê²??´ìš©???ì‹¤?©ë‹ˆ??
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using Microsoft.Dss.ServiceModel.DsspServiceBase;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Xml;
using W3C.Soap;
using dssopencv2 = Robotics.Dssopencv2;
using Microsoft.Ccr.Adapters.WinForms;

using submgr = Microsoft.Dss.Services.SubscriptionManager;
namespace Robotics.Dssopencv2
{
    
    
    /// <summary>
    /// Implementation class for Dssopencv2
    /// </summary>
    [DisplayName("Dssopencv2")]
    [Description("The Dssopencv2 Service")]
    [Contract(Contract.Identifier)]
    public class Dssopencv2Service : DsspServiceBase
    {
        CLROpenCV.MovingDetect _MovingDetect = null;
        /// <summary>
        /// _state
        /// </summary>
        [ServiceState()]
        private Dssopencv2State _state = new Dssopencv2State();
        
        /// <summary>
        /// _main Port
        /// </summary>
        [ServicePort("/dssopencv2", AllowMultipleInstances=false)]
        private Dssopencv2Operations _mainPort = new Dssopencv2Operations();


        //±¸µ¶ ±â´ÉÀ» À§ÇØ Ç×»ó Ãß°¡µÇ¾î ÇÏ´Â ÄÚµåÀÓ
        [Partner("SubMgr", Contract = submgr.Contract.Identifier, CreationPolicy = PartnerCreationPolicy.CreateAlways)]
        private submgr.SubscriptionManagerPort _submgrPort = new submgr.SubscriptionManagerPort();



        /// <summary>
        /// Default Service Constructor
        /// </summary>
        public Dssopencv2Service(DsspServiceCreationPort creationPort) : 
                base(creationPort)
        {
        }
        
        /// <summary>
        /// Service Start
        /// </summary>
        protected override void Start()
        {
			base.Start();
			// Add service specific initialization here.


            WinFormConstructor wc = new WinFormConstructor(
                delegate
                {
                    return new CLROpenCV.MovingDetect();
                }
                );

            _MovingDetect = (CLROpenCV.MovingDetect)wc.Invoke();

            WinFormsServicePort.FormInvoke(
                delegate() { _MovingDetect.Show(); }
            );

        }
    }
}
